name: '[Internal] Build and Test'

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        description: The runner selected to run on
      device:
        required: true
        type: string
        description: The device selected to run on
      image:
        required: true
        type: string
        description: The docker image which will be loaded

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    name: build torch_npu
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.image }}
      volumes:
        - /home/runner/actions-runner/codes:/root/codes
    outputs:
      dist_name: ${{ steps.list-dist.outputs.dist_name }}
    steps:
      - name: Prepare the codes
        run: |
          cp -rf /root/codes /root/build

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/dependencies-action
        with:
          pip_packages: |
            - wheel
          pip_requirements: |
            - /root/build/npu/pytorch/requirements.txt

      - name: Build torch_npu
        working-directory: /root/build/npu/pytorch
        run: |
          py_version=$(python --version | awk '{print $2}' | cut -d '.' -f 1,2)
          bash ci/build.sh --python=${py_version}

      - name: List distribution package
        id: list-dist
        working-directory: /root/build/npu/pytorch/dist
        run: |
          dist_name=$(ls torch_npu*.whl)
          dist_path=$(pwd)/${dist_name}
          echo "dist_name=${dist_name}" >> $GITHUB_OUTPUT
          echo "dist_path=${dist_path}" >> $GITHUB_OUTPUT

      - name: Upload distribution artifact
        id: upload-dist
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.list-dist.outputs.dist_name }}
          path: ${{ steps.list-dist.outputs.dist_path }}
          retention-days: 1

      - name: Write to workflow job summary
        if: ${{ steps.upload-dist.outputs.artifact-url }}
        run: |
          echo "## torch_npu built successfully! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "You can download the distribution package [here](${{ steps.upload-dist.outputs.artifact-url }})." >> $GITHUB_STEP_SUMMARY

  test:
    name: test torch_npu in ${{ inputs.image }} with ${{ inputs.device }}
    runs-on: ${{ inputs.runner }}
    needs:
      - build
    container:
      image: ${{ inputs.image }}
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
        - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
        - /etc/ascend_install.info:/etc/ascend_install.info
        - /home/runner/actions-runner/codes:/root/codes
      options: >-
        --network host
        --device ${{ inputs.device }}
        --device /dev/davinci_manager
        --device /dev/devmm_svm
        --device /dev/hisi_hdc
    steps:
      - name: Show NPU info
        run: |
          npu-smi info

      - name: Prepare the codes
        run: |
          cp -rf /root/codes /root/build

      - name: Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.dist_name }}
          path: /root/build

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/dependencies-action
        with:
          pip_packages: |
            - wheel
            - unittest-xml-reporting
          pip_requirements: |
            - /root/build/npu/pytorch/requirements.txt
            - /root/build/npu/pytorch/requirements.txt
            - /root/build/npu/pytorch/test/requirements.txt --no-deps

      - name: Install torch_npu
        working-directory: /root/build
        run: |
          pip install ${{ needs.build.outputs.dist_name }}

      - name: Do the test
        continue-on-error: true # Skip if failed
        working-directory: /root/build
        run: |
          python npu/pytorch/ci/access_control_test.py
        env:
          DISABLED_TESTS_FILE: /root/build/npu/pytorch/test/unsupported_test_cases/.pytorch-disabled-tests.json
